---
version: 2.1
jobs:
  lint_and_test_code:
    docker:
      - image: python:3.10.0-buster
    steps:
      - checkout
      - run:
          name: Install build & test dependencies
          command: |
            pip3 install --disable-pip-version-check --progress-bar off 'poetry' 'pre-commit'
            poetry config --no-interaction virtualenvs.create false
            apt-get update && apt-get install shellcheck && apt-get install direnv
      - run:
          name: Build & install
          command: poetry build --no-ansi --no-interaction && poetry install --no-ansi --no-interaction
      - run:
          name: Run pre-commit hooks on all files
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          name: Run tests
          command: |
            direnv allow
            poetry run pytest --full-trace
      - store_artifacts:
          path: dist
      - run:
          name: Test basic cli elements
          command: |
            ( set -x ; dumbpw --version ) 1>/dev/null
            ( set -x ; dumbpw --help ) 1>/dev/null

workflows:
  pipeline:
    jobs:
      - lint_and_test_code
