---
name: CodeClimate reporting

on:
  pull_request:
  push:
    branches: [main]

steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: <code_climate_reporter_id>
    with:
      coverageLocations: ${{github.workspace}}/cov/coverage.xml
