---
name: CodeClimate reporting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageLocations: ${{github.workspace}}/cov/coverage.xml
